function(enable_ipo_lto_for_release _target)
  message(STATUS "Configure IPO/LTO for ${_target}")
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "IPO/LTO disabled in debug")
  else()
    include(CheckIPOSupported)
    check_ipo_supported(RESULT ipoSupported OUTPUT ipoOutput)
    if(ipoSupported)
      message(STATUS "IPO/LTO enabled")
      set_property(TARGET ${_target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    else()
      message(STATUS "IPO/LTO not supported: ${ipoOutput}")
    endif()
  endif()
endfunction()
